'use client'

import { useEffect, useMemo, useState } from 'react'
import { ClipboardList, Plus, Search } from 'lucide-react'
import { ClinicShell, EmptyState, Field, Patient, buttonClass, cardClass, inputClass, secondaryButtonClass } from '@/components/clinic-shell'

type Checkup = { id: string; patient_id: string; patient_name?: string; diagnosis?: string; symptoms?: string; notes?: string; vitals?: Record<string, string>; created_at?: string }

export default function CheckupsPage() {
  const [patients, setPatients] = useState<Patient[]>([]), [checkups, setCheckups] = useState<Checkup[]>([]), [query, setQuery] = useState(''), [open, setOpen] = useState(false), [error, setError] = useState('')
  const [form, setForm] = useState({ patientId: '', diagnosis: '', symptoms: '', notes: '', bloodPressure: '', pulse: '', temperature: '', weight: '' })
  const load = async () => { const [patientsResponse, checkupsResponse] = await Promise.all([fetch('/api/patients'), fetch('/api/checkups')]); setPatients(await patientsResponse.json()); setCheckups(await checkupsResponse.json()) }
  useEffect(() => { load() }, [])
  const filtered = useMemo(() => checkups.filter((item) => `${item.patient_name || ''} ${item.diagnosis || ''} ${item.symptoms || ''}`.toLowerCase().includes(query.toLowerCase())), [checkups, query])
  const save = async () => { setError(''); if (!form.patientId || !form.diagnosis.trim()) return setError('Select a patient and enter a diagnosis.'); const response = await fetch('/api/checkups', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ patientId: form.patientId, diagnosis: form.diagnosis, symptoms: form.symptoms, notes: form.notes, vitals: { 'Blood pressure': form.bloodPressure, Pulse: form.pulse, Temperature: form.temperature, Weight: form.weight } }) }); if (!response.ok) return setError('Could not save checkup.'); setForm({ patientId: '', diagnosis: '', symptoms: '', notes: '', bloodPressure: '', pulse: '', temperature: '', weight: '' }); setOpen(false); await load() }
  return <ClinicShell title="Checkups" description="Document consultations, symptoms, vitals, and clinical notes in one timeline." action={<button className={buttonClass} onClick={() => setOpen(true)}><Plus data-icon="inline-start" />New checkup</button>}>
    {open && <div className={`${cardClass} mb-6`}><h2 className="mb-5 text-lg font-bold">Record a checkup</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Patient"><select className={inputClass} value={form.patientId} onChange={(e) => setForm({ ...form, patientId: e.target.value })}><option value="">Select patient</option>{patients.map((p) => <option value={p.id} key={p.id}>{p.name} · {p.patient_code}</option>)}</select></Field><Field label="Diagnosis"><input className={inputClass} value={form.diagnosis} onChange={(e) => setForm({ ...form, diagnosis: e.target.value })} placeholder="Primary diagnosis" /></Field><Field label="Symptoms"><input className={inputClass} value={form.symptoms} onChange={(e) => setForm({ ...form, symptoms: e.target.value })} placeholder="Reported symptoms" /></Field><Field label="Blood pressure"><input className={inputClass} value={form.bloodPressure} onChange={(e) => setForm({ ...form, bloodPressure: e.target.value })} placeholder="120/80" /></Field><Field label="Pulse"><input className={inputClass} value={form.pulse} onChange={(e) => setForm({ ...form, pulse: e.target.value })} placeholder="72 bpm" /></Field><Field label="Temperature"><input className={inputClass} value={form.temperature} onChange={(e) => setForm({ ...form, temperature: e.target.value })} placeholder="37 °C" /></Field><Field label="Weight"><input className={inputClass} value={form.weight} onChange={(e) => setForm({ ...form, weight: e.target.value })} placeholder="kg" /></Field><Field label="Clinical notes"><textarea className="min-h-11 rounded-xl border border-[#dfe9e4] bg-white px-3 py-3 text-sm outline-none focus:border-[#58aa88] md:col-span-2" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="Assessment and follow-up plan" /></Field></div>{error && <p role="alert" className="mt-4 text-sm font-semibold text-red-600">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button className={secondaryButtonClass} onClick={() => setOpen(false)}>Cancel</button><button className={buttonClass} onClick={save}>Save checkup</button></div></div>}
    <div className="mb-5 flex items-center justify-between gap-4"><div><p className="text-3xl font-bold">{checkups.length}</p><p className="text-sm text-[#81918d]">recorded visits</p></div><label className="flex h-11 w-full max-w-sm items-center gap-2 rounded-xl border border-[#dfe9e4] bg-white px-3"><Search className="size-4 text-[#81918d]" /><input aria-label="Search checkups" className="min-w-0 flex-1 outline-none" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search patient or diagnosis" /></label></div>
    {filtered.length ? <div className="flex flex-col gap-3">{filtered.map((item) => <article className={cardClass} key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-[#e9f4ef] text-[#16805f]"><ClipboardList /></span><div><h2 className="font-bold">{item.patient_name || 'Patient'}</h2><p className="text-sm font-semibold text-[#16805f]">{item.diagnosis || 'No diagnosis'}</p></div></div><time className="text-xs font-semibold text-[#81918d]">{item.created_at ? new Date(item.created_at).toLocaleDateString() : ''}</time></div><div className="mt-4 grid gap-3 text-sm md:grid-cols-3"><p><span className="block text-xs font-bold uppercase tracking-wide text-[#98a7a1]">Symptoms</span>{item.symptoms || 'None recorded'}</p><p><span className="block text-xs font-bold uppercase tracking-wide text-[#98a7a1]">Vitals</span>{Object.entries(item.vitals || {}).filter(([, value]) => value).map(([key, value]) => `${key}: ${value}`).join(' · ') || 'Not recorded'}</p><p><span className="block text-xs font-bold uppercase tracking-wide text-[#98a7a1]">Notes</span>{item.notes || 'No notes'}</p></div></article>)}</div> : <EmptyState text={query ? 'No checkups match your search.' : 'No checkups yet. Record the first visit.'} />}
  </ClinicShell>
}
