'use client'

import { useEffect, useMemo, useState } from 'react'
import { Activity, CalendarDays, Check, ClipboardList, FileText, HeartPulse, LayoutDashboard, Menu, Pill, Plus, Search, Settings, Stethoscope, UserRound, Users, X } from 'lucide-react'

type Patient = { id: string; name: string; patient_code: string; date_of_birth?: string; gender?: string; phone?: string; allergies?: string }
type Prescription = { id: string; diagnosis: string; medicines: { name: string; dosage?: string; duration?: string; frequency?: string }[] }

const nav = [['Overview', LayoutDashboard], ['Patients', Users], ['Checkups', ClipboardList], ['Prescriptions', Pill]] as const
const diagnosisSuggestions = ['Type 2 diabetes', 'Hypertension', 'Acute bronchitis', 'Migraine', 'Seasonal allergies']
const medicineSuggestions = ['Metformin 500 mg', 'Amlodipine 5 mg', 'Cetirizine 10 mg', 'Paracetamol 650 mg']

export default function Page() {
  const [tab, setTab] = useState('Overview')
  const [patients, setPatients] = useState<Patient[]>([])
  const [selected, setSelected] = useState<Patient | null>(null)
  const [prescriptions, setPrescriptions] = useState<Prescription[]>([])
  const [diagnosis, setDiagnosis] = useState('')
  const [medicine, setMedicine] = useState('')
  const [saved, setSaved] = useState(false)
  const [mobileOpen, setMobileOpen] = useState(false)
  const [showPatientForm, setShowPatientForm] = useState(false)
  const [patientName, setPatientName] = useState('')
  const [patientPhone, setPatientPhone] = useState('')
  const [loading, setLoading] = useState(true)

  const loadPatients = async () => { const response = await fetch('/api/patients'); const data = await response.json(); setPatients(data); setSelected((current) => current || data[0] || null); setLoading(false) }
  useEffect(() => { loadPatients() }, [])
  useEffect(() => { if (selected) fetch(`/api/prescriptions?patientId=${selected.id}`).then((response) => response.json()).then(setPrescriptions) }, [selected])

  const savePatient = async () => { if (!patientName.trim()) return; const response = await fetch('/api/patients', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: patientName, phone: patientPhone }) }); const patient = await response.json(); setPatients((items) => [patient, ...items]); setSelected(patient); setPatientName(''); setPatientPhone(''); setShowPatientForm(false); setTab('Patients') }
  const savePrescription = async () => { if (!selected || !diagnosis.trim() || !medicine.trim()) return; const response = await fetch('/api/prescriptions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ patientId: selected.id, diagnosis, medicine, dosage: 'Once daily', duration: '7 days' }) }); if (response.ok) { setSaved(true); setPrescriptions((items) => [{ id: Date.now().toString(), diagnosis, medicines: [{ name: medicine, dosage: 'Once daily', duration: '7 days' }] }, ...items]); setTimeout(() => setSaved(false), 2400) } }
  const initials = (name = '') => name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase()
  const dateLabel = useMemo(() => new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'short', day: 'numeric', year: 'numeric' }).format(new Date()), [])

  return <main className="min-h-screen bg-[#f6f8f7] text-[#183b37] dark:bg-[#10211d] dark:text-[#eef8f3]">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-[248px] flex-col border-r border-[#e5ebe8] bg-white px-5 py-6 transition-transform dark:border-[#24413a] dark:bg-[#142b25] lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="mb-11 flex items-center gap-3 px-2"><div className="flex size-10 items-center justify-center rounded-xl bg-[#d9f4e8] text-[#13795b]"><Stethoscope /></div><div><div className="text-[17px] font-bold tracking-tight">MediNotes</div><div className="text-[11px] font-medium text-[#81918d]">CLINIC WORKSPACE</div></div><button onClick={() => setMobileOpen(false)} className="ml-auto lg:hidden"><X /></button></div>
      <nav className="flex flex-col gap-2" aria-label="Main navigation">{nav.map(([label, Icon]) => <button key={label} onClick={() => { setTab(label); setMobileOpen(false) }} className={`flex items-center gap-3 rounded-xl px-3.5 py-3 text-sm font-semibold transition ${tab === label ? 'bg-[#e5f7ee] text-[#16805f]' : 'text-[#73837f] hover:bg-[#f3f7f5]'}`}><Icon className="size-[18px]" />{label}{label === 'Patients' && <span className="ml-auto rounded-full bg-[#edf2ef] px-2 py-0.5 text-[11px]">{patients.length}</span>}</button>)}</nav>
      <div className="mt-auto flex flex-col gap-2 border-t border-[#edf0ef] pt-5"><button className="flex items-center gap-3 rounded-xl px-3.5 py-3 text-sm font-semibold text-[#73837f]"><Settings className="size-[18px]" />Settings</button><div className="mt-3 flex items-center gap-3 rounded-xl bg-[#f6f8f7] p-3"><div className="flex size-9 items-center justify-center rounded-full bg-[#d7e9ff] text-xs font-bold text-[#2764a5]">DS</div><div><p className="text-sm font-bold">Dr. Sarah Davis</p><p className="text-xs text-[#84918e]">General physician</p></div></div></div>
    </aside>
    {mobileOpen && <button aria-label="Close navigation" onClick={() => setMobileOpen(false)} className="fixed inset-0 z-20 bg-[#153b35]/20 lg:hidden" />}
    <section className="lg:pl-[248px]"><header className="flex h-[76px] items-center justify-between border-b border-[#e8eeeb] bg-white/80 px-5 backdrop-blur md:px-10 dark:border-[#24413a] dark:bg-[#142b25]/90"><div className="flex items-center gap-3"><button onClick={() => setMobileOpen(true)} className="lg:hidden"><Menu /></button><div><p className="text-sm text-[#81918d]">{dateLabel}</p><h1 className="text-xl font-bold tracking-tight">Good morning, Dr. Davis</h1></div></div><div className="flex items-center gap-3"><button className="flex size-10 items-center justify-center rounded-full border border-[#e6ece9] bg-white text-[#7e8d89]"><Search className="size-[18px]" /></button><div className="flex size-10 items-center justify-center rounded-full bg-[#d7e9ff] text-xs font-bold text-[#2764a5]">DS</div></div></header>
      <div className="mx-auto max-w-[1440px] px-5 py-8 md:px-10"><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-semibold uppercase tracking-[0.14em] text-[#15916b]">Clinical workspace</p><h2 className="text-[30px] font-bold tracking-[-0.04em]">{tab === 'Overview' ? 'Your practice at a glance' : tab}</h2><p className="mt-1 text-[15px] text-[#81918d]">Keep every patient visit clear, consistent, and easy to revisit.</p></div><button onClick={() => setShowPatientForm(true)} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-[#167a5b] px-5 text-sm font-bold text-white shadow-sm hover:bg-[#116a4f]"><Plus className="size-[18px]" />New patient</button></div>
        {showPatientForm && <div className="mb-6 rounded-2xl border border-[#dcefe5] bg-white p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold">Add patient</h3><button onClick={() => setShowPatientForm(false)}><X className="size-4" /></button></div><div className="grid gap-3 md:grid-cols-2"><input value={patientName} onChange={(event) => setPatientName(event.target.value)} placeholder="Full name" className="h-11 rounded-xl border border-[#e2eae6] bg-[#fbfcfb] px-3 text-sm outline-none focus:ring-2 focus:ring-[#a7e4c9]" /><input value={patientPhone} onChange={(event) => setPatientPhone(event.target.value)} placeholder="Phone number" className="h-11 rounded-xl border border-[#e2eae6] bg-[#fbfcfb] px-3 text-sm outline-none focus:ring-2 focus:ring-[#a7e4c9]" /></div><button onClick={savePatient} className="mt-4 rounded-xl bg-[#167a5b] px-4 py-2.5 text-sm font-bold text-white">Save patient</button></div>}
        <div className="mb-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Total patients', patients.length, Users], ['Today’s checkups', 12, CalendarDays], ['Saved prescriptions', prescriptions.length, FileText], ['Clinical memory', 'On', HeartPulse]].map(([label, value, Icon]) => <div key={label as string} className="rounded-2xl border border-[#e6ece9] bg-white p-5"><div className="mb-5 flex items-start justify-between"><p className="text-sm font-semibold text-[#74837f]">{label as string}</p><div className="flex size-9 items-center justify-center rounded-xl bg-[#e0f7ed] text-[#15916b]"><Icon className="size-[18px]" /></div></div><p className="text-[28px] font-bold tracking-[-0.04em]">{value as string | number}</p></div>)}</div>
        <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><div className="rounded-2xl border border-[#e6ece9] bg-white p-6"><div className="mb-5 flex items-center justify-between"><div><h3 className="text-lg font-bold">Patient records</h3><p className="mt-1 text-sm text-[#899692]">Select a patient to create a checkup or prescription.</p></div><button onClick={() => setShowPatientForm(true)} className="flex items-center gap-1 text-sm font-bold text-[#16805f]"><Plus className="size-4" />Add</button></div>{loading ? <p className="py-8 text-sm text-[#899692]">Loading records...</p> : patients.length === 0 ? <div className="rounded-xl bg-[#f6faf8] p-8 text-center"><UserRound className="mx-auto mb-2 text-[#80ad9c]" /><p className="font-semibold">No patients yet</p><p className="mt-1 text-sm text-[#899692]">Add your first patient to get started.</p></div> : <div className="flex flex-col gap-2">{patients.map((patient) => <button key={patient.id} onClick={() => { setSelected(patient); setTab('Checkups') }} className={`flex items-center gap-3 rounded-xl p-3 text-left transition hover:bg-[#f6faf8] ${selected?.id === patient.id ? 'bg-[#effaf4]' : ''}`}><div className="flex size-10 items-center justify-center rounded-full bg-[#dff5eb] text-xs font-bold text-[#208261]">{initials(patient.name)}</div><div className="min-w-0 flex-1"><p className="font-bold">{patient.name}</p><p className="text-xs text-[#91a09b]">{patient.patient_code} {patient.phone ? `• ${patient.phone}` : ''}</p></div><span className="text-xs font-semibold text-[#348b6b]">View record</span></button>)}</div>}</div>
          <div className="rounded-2xl border border-[#e6ece9] bg-white p-6"><div className="mb-6 flex items-center justify-between"><div><h3 className="text-lg font-bold">Create prescription</h3><p className="mt-1 text-sm text-[#899692]">{selected ? `For ${selected.name}` : 'Select a patient first'}</p></div><div className="flex size-10 items-center justify-center rounded-xl bg-[#e0f7ed] text-[#15916b]"><Pill className="size-[19px]" /></div></div><div className="flex flex-col gap-4"><label className="text-xs font-bold uppercase tracking-[0.08em] text-[#899692]">Diagnosis<input value={diagnosis} onChange={(event) => setDiagnosis(event.target.value)} list="diagnoses" placeholder="Start typing to reuse a diagnosis" className="mt-2 h-11 w-full rounded-xl border border-[#e2eae6] bg-[#fbfcfb] px-3 text-sm font-semibold outline-none focus:ring-2 focus:ring-[#a7e4c9]" /><datalist id="diagnoses">{diagnosisSuggestions.concat(prescriptions.map((item) => item.diagnosis)).map((item) => <option key={item} value={item} />)}</datalist></label><label className="text-xs font-bold uppercase tracking-[0.08em] text-[#899692]">Medicine<input value={medicine} onChange={(event) => setMedicine(event.target.value)} list="medicines" placeholder="Start typing to reuse a medicine" className="mt-2 h-11 w-full rounded-xl border border-[#e2eae6] bg-[#fbfcfb] px-3 text-sm font-semibold outline-none focus:ring-2 focus:ring-[#a7e4c9]" /><datalist id="medicines">{medicineSuggestions.concat(prescriptions.flatMap((item) => item.medicines.map((med) => med.name))).map((item) => <option key={item} value={item} />)}</datalist></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold uppercase tracking-[0.08em] text-[#899692]">Frequency<select className="mt-2 h-11 w-full rounded-xl border border-[#e2eae6] bg-[#fbfcfb] px-3 text-sm font-semibold outline-none"><option>Once daily</option><option>Twice daily</option><option>As needed</option></select></label><label className="text-xs font-bold uppercase tracking-[0.08em] text-[#899692]">Duration<select className="mt-2 h-11 w-full rounded-xl border border-[#e2eae6] bg-[#fbfcfb] px-3 text-sm font-semibold outline-none"><option>7 days</option><option>14 days</option><option>30 days</option></select></label></div><button onClick={savePrescription} disabled={!selected || !diagnosis.trim() || !medicine.trim()} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-[#167a5b] text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{saved ? <><Check className="size-4" />Saved to history</> : <><FileText className="size-4" />Save prescription</>}</button></div></div></div>
        <div className="mt-6 rounded-2xl border border-[#dcefe5] bg-[#effaf4] p-5"><div className="flex items-start gap-3"><div className="mt-0.5 flex size-9 shrink-0 items-center justify-center rounded-xl bg-white text-[#16805f]"><Activity className="size-[18px]" /></div><div><h3 className="text-sm font-bold text-[#1b5e48]">Clinical memory is on</h3><p className="mt-1 text-sm leading-relaxed text-[#598172]">Diagnoses and medicines from saved prescriptions are stored in Neon and appear as suggestions the next time you prescribe.</p></div></div></div>
      </div></section>
  </main>
}
