import { redirect } from 'next/navigation'
import Link from 'next/link'
import { BarChart3, ClipboardList, LogOut, Users } from 'lucide-react'
import { getRole, getSession } from '@/lib/auth'

export default async function ManagerPage() {
  const session = await getSession()
  if (!session?.user) redirect('/sign-in')
  if (getRole(session.user.email) !== 'manager') redirect('/')
  return <main className="min-h-screen bg-[#f6f8f7] px-5 py-8 text-[#183b37] dark:bg-[#10211d] dark:text-[#eef8f3]"><div className="mx-auto max-w-6xl"><header className="mb-8 flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-[#15916b]">MediNotes administration</p><h1 className="mt-2 text-3xl font-bold">Manager dashboard</h1><p className="mt-1 text-[#81918d]">Clinic operations and protected access overview.</p></div><form action="/api/auth/sign-out" method="post"><button className="inline-flex items-center gap-2 rounded-xl border border-[#dfe9e4] bg-white px-4 py-2.5 text-sm font-bold dark:bg-[#142b25]"><LogOut size={16} />Sign out</button></form></header><div className="grid gap-5 md:grid-cols-3"><section className="rounded-2xl border border-[#e6ece9] bg-white p-6 dark:bg-[#142b25]"><Users className="mb-5 text-[#15916b]" /><p className="text-sm text-[#81918d]">Staff accounts</p><p className="mt-2 text-3xl font-bold">2</p><p className="mt-2 text-sm text-[#81918d]">Doctor and manager access</p></section><section className="rounded-2xl border border-[#e6ece9] bg-white p-6 dark:bg-[#142b25]"><ClipboardList className="mb-5 text-[#15916b]" /><p className="text-sm text-[#81918d]">Workspace modules</p><p className="mt-2 text-3xl font-bold">5</p><p className="mt-2 text-sm text-[#81918d]">Patients, checkups, prescriptions, medicines</p></section><section className="rounded-2xl border border-[#e6ece9] bg-white p-6 dark:bg-[#142b25]"><BarChart3 className="mb-5 text-[#15916b]" /><p className="text-sm text-[#81918d]">Access status</p><p className="mt-2 text-3xl font-bold text-[#16805f]">Secure</p><p className="mt-2 text-sm text-[#81918d]">Server session required</p></section></div><section className="mt-6 rounded-2xl border border-[#e6ece9] bg-white p-6 dark:bg-[#142b25]"><h2 className="text-lg font-bold">Quick navigation</h2><div className="mt-4 flex flex-wrap gap-3"><Link href="/" className="rounded-xl bg-[#167a5b] px-4 py-2.5 text-sm font-bold text-white">Open clinical workspace</Link><Link href="/patients" className="rounded-xl border border-[#dfe9e4] px-4 py-2.5 text-sm font-bold">Review patients</Link></div></section></div></main>
}
