'use client'
import { useEffect, useState } from 'react'
import { Pencil, Plus, Search, Trash2, X } from 'lucide-react'
import { ClinicShell, EmptyState, Field, buttonClass, cardClass, inputClass, secondaryButtonClass } from '@/components/clinic-shell'
type Medicine = { id: string; name: string; strength?: string; form?: string; instructions?: string }
const blank = { name: '', strength: '', form: '', instructions: '' }
export default function MedicinesPage() {
  const [items, setItems] = useState<Medicine[]>([]), [query, setQuery] = useState(''), [form, setForm] = useState(blank), [editing, setEditing] = useState<string | null>(null), [open, setOpen] = useState(false), [error, setError] = useState('')
  const load = async () => { const response = await fetch('/api/medicines'); setItems(await response.json()) }
  useEffect(() => { load() }, [])
  const save = async () => { setError(''); if (!form.name.trim()) return setError('Medicine name is required.'); const response = await fetch('/api/medicines' + (editing ? `?id=${editing}` : ''), { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) return setError('Could not save medicine.'); setOpen(false); setEditing(null); setForm(blank); load() }
  const remove = async (id: string) => { if (!window.confirm('Remove this medicine from the library?')) return; await fetch(`/api/medicines?id=${id}`, { method: 'DELETE' }); load() }
  const filtered = items.filter((item) => `${item.name} ${item.strength || ''} ${item.form || ''}`.toLowerCase().includes(query.toLowerCase()))
  return <ClinicShell title="Medicine library" description="Maintain the approved medicine list used by every prescription." action={<button className={buttonClass} onClick={() => { setEditing(null); setForm(blank); setOpen(true) }}><Plus data-icon="inline-start" />Add medicine</button>}>
    {open && <div className={`${cardClass} mb-6 max-w-2xl`}><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-bold">{editing ? 'Edit medicine' : 'Add medicine'}</h2><p className="text-sm text-[#81918d]">Only medicines in this library can be selected in prescriptions.</p></div><button onClick={() => setOpen(false)} aria-label="Close"><X /></button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Medicine name"><input className={inputClass} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="e.g. Montelukast" /></Field><Field label="Strength"><input className={inputClass} value={form.strength} onChange={(e) => setForm({ ...form, strength: e.target.value })} placeholder="e.g. 10 mg" /></Field><Field label="Form"><input className={inputClass} value={form.form} onChange={(e) => setForm({ ...form, form: e.target.value })} placeholder="Tablet, syrup, inhaler" /></Field><Field label="Default instructions"><input className={inputClass} value={form.instructions} onChange={(e) => setForm({ ...form, instructions: e.target.value })} placeholder="Optional" /></Field></div>{error && <p className="mt-3 text-sm font-semibold text-red-600">{error}</p>}<div className="mt-5 flex gap-2"><button className={buttonClass} onClick={save}>Save medicine</button><button className={secondaryButtonClass} onClick={() => setOpen(false)}>Cancel</button></div></div>}
    <div className={`${cardClass} mb-6 flex items-center gap-3`}><Search className="size-4 text-[#81918d]" /><input className="min-w-0 flex-1 outline-none" aria-label="Search medicine library" placeholder="Search medicines" value={query} onChange={(e) => setQuery(e.target.value)} /><span className="text-sm text-[#81918d]">{filtered.length} medicines</span></div>
    {filtered.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <article className={cardClass} key={item.id}><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{item.name}</h2><p className="mt-1 text-sm text-[#81918d]">{[item.strength, item.form].filter(Boolean).join(' · ') || 'No strength or form added'}</p>{item.instructions && <p className="mt-3 text-sm text-[#52645d]">{item.instructions}</p>}</div><span className="rounded-full bg-[#e5f7ee] px-2 py-1 text-xs font-bold text-[#16805f]">Active</span></div><div className="mt-5 flex gap-2"><button className={secondaryButtonClass} onClick={() => { setEditing(item.id); setForm({ name: item.name, strength: item.strength || '', form: item.form || '', instructions: item.instructions || '' }); setOpen(true) }}><Pencil data-icon="inline-start" />Edit</button><button className={secondaryButtonClass} onClick={() => remove(item.id)}><Trash2 data-icon="inline-start" />Remove</button></div></article>)}</div> : <EmptyState text={query ? 'No medicines match your search.' : 'Your medicine library is empty. Add your first medicine.'} />}
  </ClinicShell>
}
